# Generated by Django 5.2.7 on 2025-10-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Exercício')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para cada exercício', max_length=100, null=True, unique=True, verbose_name='Slug do Exercício')),
                ('force', models.CharField(blank=True, max_length=50, null=True, verbose_name='Força (puxar/empurrar)')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível (iniciante)')),
                ('mechanic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mecânica (composto)')),
                ('equipment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipamento')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria (força)')),
                ('primary_muscles', models.JSONField(verbose_name='Músculos Primários')),
                ('secondary_muscles', models.JSONField(verbose_name='Músculos Secundários')),
                ('instructions', models.JSONField(verbose_name='Instruções')),
                ('images', models.JSONField(verbose_name='Caminhos das Imagens')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(verbose_name='Séries')),
                ('repeticoes', models.CharField(max_length=20, verbose_name="Repetições (Ex: 10-12 ou 'Até a falha')")),
                ('carga_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga (kg)')),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='treinos.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treino', models.CharField(max_length=50, verbose_name='Nome do Treino (Ex: Treino A)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='É o treino atual?')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='academias.aluno')),
                ('exercicios', models.ManyToManyField(through='treinos.ItemTreino', to='treinos.exercicio', verbose_name='Exercícios')),
                ('personal_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinos_criados', to='academias.personaltrainer')),
            ],
        ),
        migrations.AddField(
            model_name='itemtreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='treinos.treino'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtreino',
            unique_together={('treino', 'exercicio')},
        ),
    ]
