# Generated by Django 5.2.7 on 2025-10-22 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academias', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('cref', models.CharField(max_length=20, unique=True, verbose_name='CREF')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade')),
            ],
        ),
        migrations.AddField(
            model_name='academia',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academias_como_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('objetivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Objetivo de Treino')),
                ('personal_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academias.personaltrainer', verbose_name='Personal Trainer Responsável')),
            ],
        ),
    ]
